### ISSUE TITLE
Add AOP demo

### ISSUE THREAD

**Issue by xixingya** [snicoll/demo-aot-native#3]
Hi Stéphane:
is there have any spring aop demo using native?

**Comment by snicoll** [comment]
Hello @xixingya. Assuming you've reached this project via the blog post, please use [the recommended support channel](https://spring.io/blog/2022/09/26/native-support-in-spring-boot-3-0-0-m5).

I am not quite sure what you mean by AOP. Perhaps you mean AspectJ? This issue is of interest https://github.com/spring-projects/spring-framework/issues/28711

You can also look at the [smoke tests repository](https://github.com/spring-projects/spring-aot-smoke-tests) to see if something is matching your expectation. If you have more questions, please use Gitter or StackOverflow. Thanks!

**Comment by xixingya** [comment]
> Hello @xixingya. Assuming you've reached this project via the blog post, please use [the recommended support channel](https://spring.io/blog/2022/09/26/native-support-in-spring-boot-3-0-0-m5).
> 
> I am not quite sure what you mean by AOP. Perhaps you mean AspectJ? This issue is of interest [spring-projects/spring-framework#28711](https://github.com/spring-projects/spring-framework/issues/28711)
> 
> You can also look at the [smoke tests repository](https://github.com/spring-projects/spring-aot-smoke-tests) to see if something is matching your expectation. If you have more questions, please use Gitter or StackOverflow. Thanks!

Thanks!
